[package]
name = "cryptic-finder"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
kalosm-language-model = "0.4.1"
rbert = "0.4.0"
anyhow = "1.0.100"
rusqlite = "0.38.0"
serde = "1.0.228"
serde_json = "1.0.148"
csv = "1.4.0"
